apiVersion: v1
kind: Pod
metadata:
  name: apiapp
  labels:
    app: api
spec:
  containers:
  - name: api-container
    image: rubinder/api:latest
---
apiVersion: v1
kind: Service
metadata:
  name: apiapp-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080
