# apiVersion: v1
# kind: Pod
# metadata:
#   name: api-base
#   labels:
#     app: api-base
# spec:
#   containers:
#   - name: api-base-container
#     image: rubinder/api-base:latest
apiVersion: v1
kind: Pod
metadata:
  name: api-base
  labels:
    app: api-base
spec:
  containers:
  - name: api-base-container
    image: rubinder/api-base:latest
---
apiVersion: v1
kind: Service
metadata:
  name: api-base-service
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080